課題が現状できていません。
tpu-game-2020/comp2_12_quick_sort pull request #17
Opened 2020-12-22 07:35 UTC by shuhei-matsushima

自分なりに課題を進めていますが、Test2から通らず、どう改良したらよいのかが手詰まりです、授業の回答ではなく、今の自分のコードをどう変えればよいのかをお教えいただきたく存じます。

2020-12-22 10:37 UTC, imagire requested changes
範囲外アクセスをしているので、変数の値を確認しながらデバッグしてください。

2020-12-22 10:37 UTC, imagire commented on src/StaticLib/sort.c
> +		while (p[j].key > pivot.key)
ループの初回はjがendとなりますが、最初にa->numで入ってくるので、範囲外へのアクセスとなっています。

2020-12-22 13:50 UTC, shuhei-matsushima commented on src/StaticLib/sort.c
> +		while (p[j].key > pivot.key)
アドバイスありがとうございました。改善できました。

2020-12-28 08:52 UTC, imagire commented
LGTM

2020-12-28 08:52 UTC, closed without merging